### PR TITLE
Add NPM documentation

### PR DESCRIPTION
**Pull request by Craga89**
As discussed on https://github.com/BlueSpire/Durandal-Bower/pull/6#issuecomment-129102344, I've added some documentation of using NPM to grab Durandal.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@davismj Please review and advise. Thanks!

**Comment by davismj** [comment]
This is incomplete. You definitely can install from NPM, and NPM will install dependencies, but durandal isn't really designed to know anything about its dependencies, as they are configured in the global require config. To get it working, you'd have to go in and manually update all your dependencies. At first glance, I had to handwrite the following configuration:
```javascript
    paths: {
        'text': 'node_modules/durandal/node_modules/requirejs-text/text',
        'durandal':'node_modules/durandal/js',
        'plugins' : 'node_modules/durandal/js/plugins',
        'transitions' : 'node_modules/durandal/js/transitions',
        'knockout': 'node_modules/durandal/node_modules/knockout/build/output/knockout-latest',
        'bootstrap': 'node_modules/durandal/node_modules/bootstrap/js/bootstrap', // ?? not installed
        'jquery': 'node_modules/durandal/node_modules/jquery/dist/jquery
```

It seems to me that the return on investment of using NPM over say bower or simply cloning an existing project is very low. Thoughts, @Craga89?

**Comment by Craga89** [comment]
My use case for this relates to Webpack/Browserify, which replaces RequireJS and hence the config you discussed above.

You can see a similar setup to yours in my `webpack.config.js`  under the `alias` key https://github.com/Craga89/durandal-webpack/blob/master/webpack.config.js#L58

**Comment by davismj** [comment]
Can I clone this repo and see Webpack/Browserify in action?

**Comment by Craga89** [comment]
Definitely. Clone https://github.com/Craga89/durandal-webpack/ and run `npm run dev`, then head to `localhost:8080`

**Comment by EisenbergEffect** [comment]
@Craga89 What was involved in getting webpack and browserify up and running with Durandal. From time to time we have people asking about this for Aurelia. We've been using system.js for Aurelia but we also currently support require.js and dojo loader (which is what we supported for Durandal). Does Webpack work with ES6? Will it work with any AMD module code?

**Comment by Craga89** [comment]
@EisenbergEffect It requires some changes to the way Durandal processes and `require`s the modules. Webpack and Browserify rely on you using mostly static dependencies (i.e. `var view = require(module? : String)`) as opposed to the dynamic `require([module? : String, ...], callback : Function)` signature that RequireJS uses. 

Basiclly, rather than using `moduleId`s I've shimmed some of Durandal's internals before `app.start` is called, so that you can pass the actual modules/views directly to both the `composition` and `router`. I've started a [blog series](http://blog.craigsworks.com/durandal-and-webpack-introduction/) about it that I'm actively working on that's a little more in depth. Sufficed to say, it's not a 10 minute job to move over to it!

Webpack does indeed work with ES6 through the use of [loaders](https://webpack.github.io/docs/loaders.html), specifically the [Babeljs](https://babeljs.io/docs/setup/#webpack) loader. It also supports AMD and basically any other module syntax.

**Comment by davismj** [comment]
Looks good!

**Comment by davismj** [comment]
This document is perfect, thanks!

One small question, are the "options" configured locally (e.g. per user)
always, sometimes or never?

**Comment by davismj** [comment]
Hi Matt

Good question. Although I had global options in mind, I guess it will depend on the plugin. I would say the plugin needs to be able to define both per user and global options.

Kind Regards,
David

From: Matthew James Davis [mailto:davis.matthewjames@gmail.com]
Sent: Thursday, 11 February 2016 8:45 PM
To: David Purkiss <david@bluenickel.co.za>; BlueSpire/Durandal <reply@reply.github.com>; Johann Botha <johann@bluenickel.co.za>; Theo Van Schalkwyk <theo@bluenickel.co.za>
Subject: Extensibility Points

This document is perfect, thanks!

One small question, are the "options" configured locally (e.g. per user) always, sometimes or never?

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.

**Pull request closed without merging**
