### PR TITLE
Updated jasmine from 1.2.0 to 2.1.3.

### PR DESCRIPTION
**Pull request by maskmaster**
Modified durandals console_reporter to work with
the new 2.1-version. Also updated some of the tests
to be compatible with the new jasmine constructs.

### CODE REVIEW

**Comment by maskmaster** [comment]
Fix for BlueSpire#619

**Comment by PWKad** [comment]
@maskmaster I assume all tests are still passing?

**Comment by maskmaster** [comment]
The tests are passing, but I would like an audit on the minor changes to the tests to make sure I have not changed the semantics.

**Comment by PWKad** [comment]
@EisenbergEffect running locally it looks like everything passes and not sure why this wouldn't be a good PR to pull in.

**Pull request merged**
