### PR TITLE
feat(knockout): Update to Knockout 3.4.0

### PR DESCRIPTION
**Pull request by davismj**
Should be used in place of https://github.com/BlueSpire/Durandal/pull/680.

### CODE REVIEW

**Comment by davidparker** [comment]
hay guys, any chance we can push this onto NPM now please, causing issues now having to maintain and keep this in an outside folder, we tried to NPM direct to the commit but this wont work.

thanks

**Comment by EisenbergEffect** [comment]
Yes. I'm assigning it to myself.

**Comment by navels** [comment]
awesome.  ditto the bower package, please :)

**Comment by EisenbergEffect** [comment]
Sure thing. I believe the npm package is just the bower package published in both places. Keep me a bit of time...I'm not kidding...I threw my back out and I'm a bit limited in terms of my "screen time" as a result. I should be able to get it this week though.

**Comment by davidparker** [comment]
yeah Durandal_Bower is the repo for the npm and bower.  however  I have forked it here: https://github.com/davidparker/Durandal-Bower   and upgraded jquery, knockout, requirejs and requirejs/text   on that one,  and then just used the url in devDependancies

**Comment by davidparker** [comment]
p.s   sorry to hear about your back :-(

**Comment by EisenbergEffect** [comment]
It's all released :)

**Pull request merged**
