### PR TITLE
Added feature to cache on page data-view-path templates in order to redu...

### PR DESCRIPTION
**Pull request by gogocat**
...ce durandal template request.

### CODE REVIEW

**Comment by PWKad** [comment]
Hey can you please give a bit better description of the issue backing this?  Were you able to open an issue before hand indicating what the problem was that causes the need for this PR?

**Comment by gogocat** [comment]
Sure. I will raise an issue. 
The feature added is to make Durandal like Angular... when it do a template ajax call, it will check if there a template in DOM. If so, it will use it and stop the ajax call. 
This is useful when you want to render something on first load that is easier/cheap by server side language. eg Razor view in .Net

**Comment by davismj** [comment]
I will review this PR

**Comment by gogocat** [comment]
It has been closed as discussed by Eisenberg
https://github.com/BlueSpire/Durandal/issues/629

**Pull request closed without merging**
