### PR TITLE
Update http.js

### PR DESCRIPTION
**Pull request by kye**
Added method suggested in issue #663.

### CODE REVIEW

**Comment by kye** [comment]
Added an ajax request method to the http.js plugin so that callers can specify a beforeSend callback.

**Comment by EisenbergEffect** [comment]
@davismj When you get a free moment, would you review this and consider if we should add it. Thanks!

**Comment by davismj** [comment]
@EisenbergEffect i recommend we close this. its a great idea and highlighted a need for a general ajax function on the http plugin, but it only added one of the numerous jquery ajax settings parameters. i have created a pull request [here](https://github.com/BlueSpire/Durandal/pull/667) that adds generalizes on the pull request here

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.

**Pull request closed without merging**
