### PR TITLE
upgraded to knockout 3.4.0

### PR DESCRIPTION
**Pull request by davidparker**
as requested in the google groups chat, I have manually upgraded knockout and durandal on my system.   It is quite an extensive system.   I have then ran all test and the new knockout presented no issue.

So I have fully upgraded Durandal to use knockout 3.4.0   including all references etc

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@davismj Are you able to review this PR?

**Comment by davidparker** [comment]
just wanted to clear up my confusing first comment.   I have built a large admin style system that uses durandal.   What I have done is manually upgraded durandal within that system.   As it uses everything durandal is capable of.    This was a good test to make sure the upgrade would work, without touching the real durandal repo.    This worked out all fine, no issues, no errors.  Also as expected you can see the memory gains. 

Once all this was done,  and I was happy that durandal could handle knockout 3.4.0.   I then upgraded the real repo.  Hence my PR.

I Just read my first comment and said MEH   to my own comment  :-)

**Comment by bleuetnoir** [comment]
+1 about memory leak issues solved by using a more recent version of knockout.

**Comment by davismj** [comment]
@EisenbergEffect It seems to be good but several of the starter kits are missing the new knockout lib. I'll revise and resubmit.

**Comment by davismj** [comment]
@EisenbergEffect This PR should be closed. Use https://github.com/BlueSpire/Durandal/pull/684 instead, which adds some fixes to this PR.

**Pull request closed without merging**
